/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-My-First-Plugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : My First Plugin
 #	author : miyako
 #	2022/08/19
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MY_FIRST_PLUGIN_H
#define PLUGIN_MY_FIRST_PLUGIN_H

#include "4DPluginAPI.h"

#pragma mark -

void My_First_Plugin_Command(PA_PluginParameters params);

#endif /* PLUGIN_MY_FIRST_PLUGIN_H */
