/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-My-First-Plugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : My First Plugin
 #	author : miyako
 #	2022/08/19
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-My-First-Plugin.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- My First Plugin
            
			case 1 :
				My_First_Plugin_Command(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void My_First_Plugin_Command(PA_PluginParameters params) {

}

